/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nightm4re.comisariav2.vista;

import com.nightm4re.comisariav2.Controller;
import com.nightm4re.comisariav2.modelo.SospechosoEntity;
import com.nightm4re.comisariav2.utils.Utils;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.Box.Filler;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nightm4re
 */
public class VistaPrincipal extends javax.swing.JFrame {

    VistaData vistadata = new VistaData();
    int contador = 1;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();

        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDialog = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        addContainer = new javax.swing.JPanel();
        addScrollVisor = new javax.swing.JScrollPane();
        addImagesVisor = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0));
        addImage = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nombreAddField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dniAddField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nacionalidadAddField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        antecedentesAddArea = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        direccionesAddArea = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        matriculasAddArea = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        numerosAddArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        datosExtraAddArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        correosAddArea = new javax.swing.JTextArea();
        imageChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 90), new java.awt.Dimension(0, 90), new java.awt.Dimension(32767, 90));
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreEditField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dniEditField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nacionalidadEditField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        antecedentesEditArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        direccionesEditArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        matriculasEditArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        numerosEditArea = new javax.swing.JTextArea();
        editScrollVisor = new javax.swing.JScrollPane();
        editImageVisor = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0));
        addImageEdit = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        datosextraEditArea = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        correosEditArea = new javax.swing.JTextArea();
        saveEdit = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        addDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addDialog.setResizable(false);
        addDialog.setSize(new java.awt.Dimension(504, 712));

        jScrollPane8.setPreferredSize(new java.awt.Dimension(504, 1361));

        addContainer.setBackground(new java.awt.Color(255, 255, 255));
        addContainer.setPreferredSize(new java.awt.Dimension(455, 1340));

        addScrollVisor.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        addScrollVisor.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        addScrollVisor.setAutoscrolls(true);
        addScrollVisor.setMaximumSize(new java.awt.Dimension(900000, 258));
        addScrollVisor.setMinimumSize(new java.awt.Dimension(102, 119));

        addImagesVisor.setBackground(new java.awt.Color(249, 249, 249));
        addImagesVisor.setMaximumSize(new java.awt.Dimension(900000, 258));
        addImagesVisor.setMinimumSize(new java.awt.Dimension(0, 0));
        addImagesVisor.setName("addImagesVisor"); // NOI18N
        addImagesVisor.setPreferredSize(new java.awt.Dimension(100, 100));
        addImagesVisor.setLayout(new javax.swing.BoxLayout(addImagesVisor, javax.swing.BoxLayout.LINE_AXIS));

        filler2.setName("NOTTHIS"); // NOI18N
        addImagesVisor.add(filler2);

        addImage.setBackground(new java.awt.Color(255, 255, 255));
        addImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anadir-imagen.png"))); // NOI18N
        addImage.setMaximumSize(new java.awt.Dimension(50, 50));
        addImage.setMinimumSize(new java.awt.Dimension(50, 50));
        addImage.setPreferredSize(new java.awt.Dimension(50, 50));
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });
        addImagesVisor.add(addImage);

        addScrollVisor.setViewportView(addImagesVisor);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("DNI");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nacionalidad");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Antecedentes");

        antecedentesAddArea.setColumns(20);
        antecedentesAddArea.setRows(5);
        jScrollPane10.setViewportView(antecedentesAddArea);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Direcciones");

        direccionesAddArea.setColumns(20);
        direccionesAddArea.setRows(5);
        jScrollPane11.setViewportView(direccionesAddArea);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Matriculas");

        matriculasAddArea.setColumns(20);
        matriculasAddArea.setRows(5);
        jScrollPane12.setViewportView(matriculasAddArea);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Numeros de teléfono");

        numerosAddArea.setColumns(20);
        numerosAddArea.setRows(5);
        jScrollPane13.setViewportView(numerosAddArea);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Datos extra");

        datosExtraAddArea.setColumns(20);
        datosExtraAddArea.setRows(5);
        jScrollPane14.setViewportView(datosExtraAddArea);

        saveButton.setBackground(new java.awt.Color(0, 204, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disco-flexible.png"))); // NOI18N
        saveButton.setText("GUARDAR");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/borrar.png"))); // NOI18N
        cancelButton.setText("CANCELAR");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Correos");

        correosAddArea.setColumns(20);
        correosAddArea.setRows(5);
        jScrollPane17.setViewportView(correosAddArea);

        javax.swing.GroupLayout addContainerLayout = new javax.swing.GroupLayout(addContainer);
        addContainer.setLayout(addContainerLayout);
        addContainerLayout.setHorizontalGroup(
            addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addContainerLayout.createSequentialGroup()
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel9))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel12))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dniAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacionalidadAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel10))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel11))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(addContainerLayout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(jLabel15))
                                .addGroup(addContainerLayout.createSequentialGroup()
                                    .addGap(166, 166, 166)
                                    .addComponent(jLabel16))
                                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane14)
                                    .addComponent(jScrollPane13)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addContainerLayout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addComponent(jLabel14))
                                .addGroup(addContainerLayout.createSequentialGroup()
                                    .addGap(153, 153, 153)
                                    .addComponent(jLabel13)))))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addScrollVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        addContainerLayout.setVerticalGroup(
            addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addScrollVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dniAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nacionalidadAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jScrollPane8.setViewportView(addContainer);

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        jScrollPane8.getVerticalScrollBar().setUnitIncrement(150);

        imageChooser.setCurrentDirectory(new java.io.File("C:\\Users"));
        imageChooser.setFileFilter(new FileNameExtensionFilter("Imagenes JPG o PNG", "jpg", "png", "jpeg"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 900));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.setRowHeight(30);
        dataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dataTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(dataTable);
        dataTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if(!event.getValueIsAdjusting()){
                    System.out.println("##### ACTIVANDO LISTENER");
                    clearFields(editScrollVisor);
                    clearFields(editImageVisor);
                    if(dataTable.getSelectedRow() != -1){
                        try{
                            getSospData(Controller.getController().getSospechosoByID(dataTable.getSelectedRow()));
                            vistadata.removeAllMapEdit();
                            switchEditFields(true);
                        }catch(Exception ex){
                            System.out.println(ex.getMessage());
                            Utils.LogToFile(ex);
                        }
                    }else{
                        switchEditFields(false);
                    }
                }
            }
        });

        jScrollPane2.getVerticalScrollBar().setUnitIncrement(150);

        searchField.setText("Buscar...");

        addButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        addButton.setText("Añadir registro");
        addButton.setMargin(new java.awt.Insets(2, 8, 2, 8));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        deleteButton.setText("Eliminar registro");
        deleteButton.setMargin(new java.awt.Insets(2, 8, 2, 8));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos del sospechoso");

        jScrollPane1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        nombreEditField.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        nombreEditField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("DNI");

        dniEditField.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        dniEditField.setEnabled(false);
        dniEditField.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nacionalidad");

        nacionalidadEditField.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        nacionalidadEditField.setEnabled(false);
        nacionalidadEditField.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Antecedentes");

        antecedentesEditArea.setColumns(20);
        antecedentesEditArea.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        antecedentesEditArea.setRows(5);
        antecedentesEditArea.setEnabled(false);
        antecedentesEditArea.setFocusable(false);
        jScrollPane3.setViewportView(antecedentesEditArea);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Direcciones");

        direccionesEditArea.setColumns(20);
        direccionesEditArea.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        direccionesEditArea.setRows(5);
        direccionesEditArea.setEnabled(false);
        direccionesEditArea.setFocusable(false);
        jScrollPane4.setViewportView(direccionesEditArea);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Matriculas");

        matriculasEditArea.setColumns(20);
        matriculasEditArea.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        matriculasEditArea.setRows(5);
        matriculasEditArea.setEnabled(false);
        matriculasEditArea.setFocusable(false);
        jScrollPane5.setViewportView(matriculasEditArea);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Numeros de teléfono");

        numerosEditArea.setColumns(20);
        numerosEditArea.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        numerosEditArea.setRows(5);
        numerosEditArea.setEnabled(false);
        numerosEditArea.setFocusable(false);
        jScrollPane6.setViewportView(numerosEditArea);

        editImageVisor.setLayout(new javax.swing.BoxLayout(editImageVisor, javax.swing.BoxLayout.LINE_AXIS));

        filler3.setName("NOTTHIS"); // NOI18N
        editImageVisor.add(filler3);

        addImageEdit.setBackground(new java.awt.Color(255, 255, 255));
        addImageEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anadir-imagen.png"))); // NOI18N
        addImageEdit.setEnabled(false);
        addImageEdit.setMaximumSize(new java.awt.Dimension(50, 50));
        addImageEdit.setMinimumSize(new java.awt.Dimension(50, 50));
        addImageEdit.setPreferredSize(new java.awt.Dimension(50, 50));
        addImageEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageEditActionPerformed(evt);
            }
        });
        editImageVisor.add(addImageEdit);

        editScrollVisor.setViewportView(editImageVisor);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Datos extra");

        datosextraEditArea.setColumns(20);
        datosextraEditArea.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        datosextraEditArea.setRows(5);
        datosextraEditArea.setEnabled(false);
        datosextraEditArea.setFocusable(false);
        jScrollPane15.setViewportView(datosextraEditArea);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Correos");

        correosEditArea.setColumns(20);
        correosEditArea.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        correosEditArea.setRows(5);
        correosEditArea.setEnabled(false);
        correosEditArea.setFocusable(false);
        jScrollPane16.setViewportView(correosEditArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addComponent(nombreEditField)
                    .addComponent(editScrollVisor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel17))
                                    .addGap(21, 21, 21))
                                .addComponent(jLabel18))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .addComponent(jScrollPane16)
                            .addComponent(nacionalidadEditField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(dniEditField)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editScrollVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dniEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nacionalidadEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jScrollPane1.setViewportView(jPanel2);

        saveEdit.setText("Guardar edición");
        saveEdit.setEnabled(false);
        saveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "DNI", "Nacionalidad", "Antecedentes", "Direcciones", "Correos", "Matriculas", "Telefonos", "Datos extra" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(saveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveEdit)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (dataTable.getSelectedRow() != -1) {
            Controller.getController().deleteSospechoso(dataTable.getSelectedRow());
            updateTable();
            clearFields(editScrollVisor);
            clearFields(editImageVisor);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addDialog.setVisible(true);
        addDialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        Boolean isValid = Controller.getController().addSospechoso(nombreAddField.getText(), dniAddField.getText(), nacionalidadAddField.getText(), antecedentesAddArea.getText(),
                correosAddArea.getText(), direccionesAddArea.getText(), matriculasAddArea.getText(), numerosAddArea.getText(), datosExtraAddArea.getText(), vistadata.getAllUrls());
        if (!isValid) {
            JOptionPane.showMessageDialog(this, "Hubo un error añadiendo el registro.", "ATENCIÓN", JOptionPane.INFORMATION_MESSAGE);
        } else {
            clearFields(addImagesVisor);
            clearFields(addContainer);
            vistadata.removeAllMap();
            addDialog.setVisible(false);
        }
        updateTable();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        addImageToVisor();

    }//GEN-LAST:event_addImageActionPerformed


    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "¿Estás seguro? Los datos introducidos se desecharan", "ATENCIÓN", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            clearFields(addImagesVisor);
            clearFields(addContainer);
            vistadata.removeAllMap();
            addDialog.setVisible(false);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditActionPerformed
        Controller.getController().editSospechoso(dataTable.getSelectedRow(), nombreAddField.getText(), dniAddField.getText(), nacionalidadAddField.getText(), antecedentesAddArea.getText(),
                correosAddArea.getText(), direccionesAddArea.getText(), matriculasAddArea.getText(), numerosAddArea.getText(), datosExtraAddArea.getText(), vistadata.getAllUrlsEdit(), vistadata.getAllNewUrlsEdit());
    }//GEN-LAST:event_saveEditActionPerformed

    private void addImageEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageEditActionPerformed
        addImageToEditVisor(null, null);
    }//GEN-LAST:event_addImageEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addContainer;
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton addImage;
    private javax.swing.JButton addImageEdit;
    private javax.swing.JPanel addImagesVisor;
    private javax.swing.JScrollPane addScrollVisor;
    private javax.swing.JTextArea antecedentesAddArea;
    private javax.swing.JTextArea antecedentesEditArea;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea correosAddArea;
    private javax.swing.JTextArea correosEditArea;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextArea datosExtraAddArea;
    private javax.swing.JTextArea datosextraEditArea;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextArea direccionesAddArea;
    private javax.swing.JTextArea direccionesEditArea;
    private javax.swing.JTextField dniAddField;
    private javax.swing.JTextField dniEditField;
    private javax.swing.JPanel editImageVisor;
    private javax.swing.JScrollPane editScrollVisor;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JFileChooser imageChooser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea matriculasAddArea;
    private javax.swing.JTextArea matriculasEditArea;
    private javax.swing.JTextField nacionalidadAddField;
    private javax.swing.JTextField nacionalidadEditField;
    private javax.swing.JTextField nombreAddField;
    private javax.swing.JTextField nombreEditField;
    private javax.swing.JTextArea numerosAddArea;
    private javax.swing.JTextArea numerosEditArea;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveEdit;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

    private void clearFields(Container panel) {

        for (Component componente : panel.getComponents()) {
            if (componente instanceof JLabel) {
                if (componente.getName() != null) {
                    if (componente.getName().startsWith("image")) {
                        panel.remove(componente);
                    }

                }

            }

            if (componente instanceof Box.Filler) {
                System.out.println("ENTRA");
                if (componente.getName() == null) {

                    panel.remove(componente);

                }

            }
        }

        updateContainer(panel);

        for (Component componente : panel.getComponents()) {
            if (componente instanceof JTextField) {
                ((JTextField) componente).setText("");
            }

            if (componente instanceof JTextArea) {
                ((JTextArea) componente).setText("");
            }

            if (componente instanceof JScrollPane) {
                for (Component comp : ((JScrollPane) componente).getComponents()) {
                    if (comp instanceof JTextArea) {
                        ((JTextArea) comp).setText("");
                    }

                    if (comp instanceof JTextField) {
                        ((JTextField) comp).setText("");
                    }
                }
            }
        }

    }

    private void addImageToVisor() throws HeadlessException {
        JLabel nuevoLabel = null;
        boolean fixed = false;
        Icon icono = null;

        if (imageChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivo = imageChooser.getSelectedFile();
            if (archivo.exists() && archivo.isFile() && archivo.canRead()) {

                BufferedImage image = null;
                try {
                    image = ImageIO.read(new File(imageChooser.getSelectedFile().getAbsolutePath()));
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Hubo un error leyendo el archivo.", "ERROR DE LECTURA", JOptionPane.ERROR_MESSAGE);
                    Utils.LogToFile(e);
                }

                if (image != null) {

                    Dimension imageDimension = Utils.getScaledDimension(new Dimension(image.getWidth(), image.getHeight()),
                            new Dimension(addScrollVisor.getWidth() / 4 - 10, addScrollVisor.getHeight() / 2 - 10));

                    Image resImage = image.getScaledInstance((int) imageDimension.getWidth(),
                            (int) imageDimension.getHeight(), Image.SCALE_SMOOTH);

                    icono = new ImageIcon(resImage);

                    nuevoLabel = new JLabel("", icono, JLabel.CENTER);
                    vistadata.addJlabelUrl(nuevoLabel, imageChooser.getSelectedFile().getAbsolutePath());
                    String nombre = "image" + String.valueOf(addImagesVisor.getComponentCount() + contador);
                    contador++;
                    nuevoLabel.setName(nombre);
                    nuevoLabel.setSize(addScrollVisor.getWidth() / 4, addScrollVisor.getHeight() / 2);
                    nuevoLabel.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {

                            vistadata.removeJlabelUrl((JLabel) e.getComponent());
                            addImagesVisor.remove(e.getComponent());
                            removeOneFiller(addImagesVisor, 1);
                            updateContainer(addImagesVisor);
                        }

                    });
                    addImagesVisor.add(Box.createRigidArea(new Dimension(10, 0)));
                    addImagesVisor.add(nuevoLabel);

                    nuevoLabel.setIcon(new ImageIcon(resImage));
                    nuevoLabel.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se puede leer el archivo.\n Compruebe los permisos de lectura.", "ERROR DE LECTURA", JOptionPane.ERROR_MESSAGE);

            }

            updateContainer(addImagesVisor);
        }
    }

    private void updateContainer(Container panel) {
        panel.revalidate();
        panel.repaint();
    }

    private void updateTable() {
        dataTable.setModel(Controller.getController().getSospechosos());
    }

    private void getSospData(SospechosoEntity sosp) {
        chargeFields(sosp.getNombre(), sosp.getDni(), sosp.getNacionalidad(), sosp.getAntecedentesString(), sosp.getDireccionesString(),
                sosp.getCorreosString(), sosp.getDatosextraString(), sosp.getMatriculasString(), sosp.getTelefonosString(), sosp.getFotosString());
        chargeImages((int) sosp.getId());

    }

    private void chargeImages(int id) {

        try {

            Map<Integer, ArrayList> map = Controller.getController().getImagenesFromSosp(id);
            ArrayList<BufferedImage> images = map.get(0);
            ArrayList<String> imagedir = map.get(1);

            if (images != null && imagedir != null && images.size() != 0 && imagedir.size() != 0) {
                for (int i = 0; i < images.size(); i++) {
                    System.out.println("IMAGE " + i + " / " + images.size() + " || " + imagedir.size());
                    addImageToEditVisor(images.get(i), imagedir.get(i));
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            Utils.LogToFile(e);

        }

    }

    private void chargeFields(String name, String dni, String nacionalidad, String antecedentes, String direcciones, String correos, String datosextra, String matriculas, String numeros, String fotos) {
        nombreEditField.setText(name);
        dniEditField.setText(dni);
        nacionalidadEditField.setText(nacionalidad);
        antecedentesEditArea.setText(antecedentes);
        direccionesEditArea.setText(direcciones);
        numerosEditArea.setText(numeros);
        correosEditArea.setText(correos);
        matriculasEditArea.setText(matriculas);
        datosextraEditArea.setText(datosextra);

    }

    private void addImageToEditVisor(BufferedImage img, String filepath) {

        JLabel nuevoLabel = null;
        Icon icono = null;
        boolean isNewImage = false;

        if (img == null) {
            isNewImage = true;
        }

        if (isNewImage) {
            if (imageChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File archivo = imageChooser.getSelectedFile();
                if (archivo.exists() && archivo.isFile() && archivo.canRead()) {

                    filepath = imageChooser.getSelectedFile().getAbsolutePath();
                    if (archivo.canRead()) {

                        try {
                            img = ImageIO.read(new File(imageChooser.getSelectedFile().getAbsolutePath()));

                        } catch (IOException e) {
                            JOptionPane.showMessageDialog(this, "Hubo un error leyendo el archivo.", "ERROR DE LECTURA", JOptionPane.ERROR_MESSAGE);
                            Utils.LogToFile(e);
                        }
                    }

                }
            }
        }

        if (img != null) {
            Dimension imageDimension = Utils.getScaledDimension(new Dimension(img.getWidth(), img.getHeight()),
                    new Dimension(editScrollVisor.getWidth() / 4 - 10, editScrollVisor.getHeight() / 2 - 10));

            Image resImage = img.getScaledInstance((int) imageDimension.getWidth(),
                    (int) imageDimension.getHeight(), Image.SCALE_SMOOTH);

            icono = new ImageIcon(resImage);

            nuevoLabel = new JLabel("", icono, JLabel.CENTER);
            if (isNewImage) {
                vistadata.addNewJlabelUrlEdit(nuevoLabel, filepath);
            } else {
                vistadata.addJlabelUrlEdit(jLabel1, filepath);
            }

            String nombre = "image" + String.valueOf(editImageVisor.getComponentCount() + contador);
            contador++;
            nuevoLabel.setName(nombre);
            nuevoLabel.setSize(editScrollVisor.getWidth() / 4, editScrollVisor.getHeight() / 2);

            editImageVisor.add(Box.createRigidArea(new Dimension(10, 0)));
            editImageVisor.add(nuevoLabel);

            nuevoLabel.setIcon(new ImageIcon(resImage));
            nuevoLabel.setVisible(true);

            if (!isNewImage) {
                nuevoLabel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        vistadata.removeNewJlabelUrlEdit((JLabel) e.getComponent());
                        editImageVisor.remove(e.getComponent());
                        removeOneFiller(editImageVisor, 1);
                        updateContainer(editImageVisor);
                    }

                });
            } else {
                nuevoLabel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        vistadata.removeNewJlabelUrlEdit((JLabel) e.getComponent());
                        editImageVisor.remove(e.getComponent());
                        removeOneFiller(editImageVisor, 1);
                        updateContainer(editImageVisor);
                    }
                });
            }
        }

        updateContainer(editImageVisor);

    }

    private void switchEditFields(boolean isEnabled) {
        nombreEditField.setEnabled(isEnabled);
        dniEditField.setEnabled(isEnabled);
        nacionalidadEditField.setEnabled(isEnabled);
        antecedentesEditArea.setEnabled(isEnabled);
        correosEditArea.setEnabled(isEnabled);
        direccionesEditArea.setEnabled(isEnabled);
        matriculasEditArea.setEnabled(isEnabled);
        datosextraEditArea.setEnabled(isEnabled);
        numerosEditArea.setEnabled(isEnabled);
        addImageEdit.setEnabled(isEnabled);
        saveEdit.setEnabled(isEnabled);
    }

    private void removeOneFiller(Container panel, int fillerstoremove) {
        int cuenta = 0;
        for (Component componente : panel.getComponents()) {
            if (cuenta < fillerstoremove) {
                if (componente instanceof Box.Filler) {
                    System.out.println("ENTRA");
                    if (componente.getName() == null) {
                        panel.remove(componente);
                        cuenta++;
                    }

                }
            }

        }

    }

}
